name: qrserv
description: Transfer files with ease over a network.

publish_to: 'none'

version: 1.4.1+28

environment:
    sdk: '>=2.17.0-182.1.beta <3.0.0'

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    intl: ^0.17.0

    sliding_up_panel: ^2.0.0+1
    path_provider: ^2.0.11
    filesize: ^2.0.1
    qr_flutter: ^4.0.0
    watcher: ^1.0.1
    package_info_plus: ^1.4.0
    url_launcher: ^6.1.5
    flutter_statusbarcolor_ns: ^0.4.0
    auto_size_text: ^3.0.0
    oktoast: ^3.2.0
    share_plus: ^4.0.10+1
    receive_sharing_intent: ^1.4.5
    file_picker: ^4.5.1
    async_zip: ^0.0.2

    window_size:
        git:
            url: https://github.com/google/flutter-desktop-embedding.git
            path: plugins/window_size
            ref: a738913c8ce2c9f47515382d40827e794a334274

dev_dependencies:
    flutter_test:
        sdk: flutter
    integration_test:
        sdk: flutter

flutter:
    uses-material-design: true
    generate: true

    fonts:
        - family: Poppins
          fonts:
              - asset: fonts/Poppins-Regular.ttf
